### ISSUE TITLE
failure in uploadPipeline() doesn't result in a build step failure

### ISSUE THREAD

**Issue by pmenglund** [chronotc/monorepo-diff-buildkite-plugin#101]
I had an error in the generated pipeline, which resulted in
```
ERRO[2022-09-20T16:51:02Z] +++ failed to upload pipeline: command `buildkite-agent` failed: exit status 1
```
but the step wasn't marked as a failure

<img width="1154" alt="Screen Shot 2022-09-20 at 09 59 29" src="https://user-images.githubusercontent.com/32618/191319514-2767d23f-f2ee-4309-9957-fa84cd4e97cc.png">

I had to enable debug output to see what was wrong
<img width="1127" alt="Screen Shot 2022-09-20 at 11 06 20" src="https://user-images.githubusercontent.com/32618/191331971-82c209d5-2ae8-488f-82ef-08852b4bc53f.png">

**Comment by evalsocket** [comment]
+1 we also faced same issue
