### ISSUE TITLE
Does this still work if one build agent is chopping and changing between multiple temporary PR branches?

### ISSUE THREAD

**Issue by paul-hammant** [chronotc/monorepo-diff-buildkite-plugin#18]
File `last_successful_build contains` SHA1s. But it doesn't contain branch name info. By default BuildKite will hand build jobs for any pushed branch to any available agent.

If one BK agent builds `master`, then `quick-fix-117-branch` (tha was waaay behind master) then `master` again, will **monorepo-diff-buildkite-plugin** do the right thing?

**Comment by chronotc** [comment]
Hi @paul-hammant, as you pointed out the plugin does not have any idea of branches.
To work around this issue we've always pulled `master` inside our diff script (this isn't provided in the plugin) to ensure that when the diff occurs, you get the expected output. What we've seen is that an agent will simply grab the branch for the build and will have a "stale" `master` which produces unexpected results.

**Comment by paul-hammant** [comment]
So this plugin would be best constrained to operate on builds for `master` and not for pull request branches (that would later get merged into master - assuming GitHub-Flow). Right?

**Comment by chronotc** [comment]
Yep, there's very little setup for operating builds on master especially if you squash commits before merging as you can simply use HEAD~1 to determine what to build.
In terms of pull-request, it requires a bit of customization in terms of writing a script to determine what to build. For us, we generally pull master from remote and run a diff against the commit for the build.

**Comment by chronotc** [comment]
Another way that we work around this problem is also rebasing frequently with master so the branches generally have the latest master when a PR is created.

As you have iterated, the plugin does not directly solve the problem of building old branches. You will need custom plumbing for that.

**Comment by paul-hammant** [comment]
OK thanks for this advice. In the end, I don't think the plugin is what I need.
