### ISSUE TITLE
README confusion for "command"

### ISSUE THREAD

**Issue by paul-hammant** [chronotc/monorepo-diff-buildkite-plugin#19]
![image](https://user-images.githubusercontent.com/82182/63019187-86591b00-be92-11e9-8600-93106fdd28f2.png)

Command is a space-separated English sentence there. I'd have guessed that should be an installed command like `make <args>`, or `./myBuildScript.sh` so am confused as to what I learn from what is in the screen-shot.

Indeed, the simple and more complex examples inline atop the README, don't have `command` nodes in the YAML, just `trigger`.

**Comment by chronotc** [comment]
Hi @paul-hammant, thank you for your feedback.
I think it's fair that the command section isn't obvious.

Would you be able to provide a PR with what would be a more helpful example and I'll have it merged in straight away.

**Comment by paul-hammant** [comment]
I would not know what to change it to, as I don't understand the documentation enough to operationalizae this plugin :-(
