### ISSUE TITLE
Add support for commands

### ISSUE THREAD

**Issue by chronotc** [chronotc/monorepo-diff-buildkite-plugin#21]
Currently this plugin only supports trigger steps.
May be useful to support command steps as well......

**Comment by jwarner112** [comment]
:+1: I would love to see that. I'm currently importing this to use in our organization ... right now I have to make a bunch of separate pipelines in Buildkite for the other jobs, as opposed to just running `buildkite-agent pipeline upload <path-to-job-YAML>`, which would be all I need out of this.

**Comment by jwarner112** [comment]
Also relevant to this is #19 which, I believe, confuses that `command` section for what this regards.

**Comment by jwarner112** [comment]
I took a look at putting this in, myself (perhaps foolishly, never having done BATS or Buildkite plugins before) and was unable to run the tests. Used Ubuntu's `bats` package, which installs `version 0.4.0`. It was unable to load the `/usr/share/lib/bats/load.bats` library since the package I used didn't install such a file.

**Comment by chronotc** [comment]
Hey @jwarner112, thanks for looking into this. I've only run it through docker as specified in https://github.com/buildkite-plugins/buildkite-plugin-tester. I hope this somehow helps?

On another note, now that GIthub actions is in public beta, there's actually less of a need to use this tool for people using github as their source control. (Github actions provide filters on branches and file paths).

**Comment by jwarner112** [comment]
> On another note, now that GIthub actions is in public beta, there's actually less of a need to use this tool for people using github as their source control. (Github actions provide filters on branches and file paths).

I'm glad you pointed that out, and I'll bring that back to my team and see if we can lean on the organization to adopt it. In the meantime I'll have to try to figure out how to do this without them. Still, thanks!

**Comment by chronotc** [comment]
Added support with #30

**Comment by jwarner112** [comment]
In the time since I last posted on this I've left the place I was at that used Buildkite, but if I go to another that does I look forward to trying this out! :P
