### ISSUE TITLE
Add example for handling "Unable to trigger builds from this pipeline -- no Buildkite user associated" error

### ISSUE THREAD

**Issue by jwarner112** [chronotc/monorepo-diff-buildkite-plugin#23]
Hey there,

A running version of this pipeline was finally established. Unfortunately, I was immediately faced with a failure containing this message:

```
2019-10-04 19:33:57 FATAL  Failed to upload and process pipeline: POST https://agent.buildkite.com/v3/jobs/dc24201f-b239-4dd9-87c3-aeeb82c72a21/pipelines: 422 Builds cannot be triggered from this pipeline as there is no Buildkite user linked to this build. Ensure that a user has added "jwarner112@users.noreply.github.com" as a verified email address on their account.
```

I took a look at the difference in ENV between this step and the one that triggered it without issue... they both say the same thing, so I'm not sure what the problem is:

```
BUILDKITE_BUILD_CREATOR="jwarner112"
BUILDKITE_BUILD_CREATOR_EMAIL="jwarner112@users.noreply.github.com"
BUILDKITE_BUILD_CREATOR_TEAMS=""
```

One way of handling this is to do as the message asks. However I've got rather a lot of people that I would have to get to do this, and nobody has ever encountered this before. Have you? If so, would you add an example of facing this issue and your workaround?

(I realize this could be handled at multiple levels, this level just has the smallest scope and I'm hoping you have a workaround)

**Comment by jwarner112** [comment]
Around the time I made this I also sent out a support email to Buildkite. I woke up this morning to a response from @keithpitt that the issue had been bugging a bunch of people and that it had finally been fixed. So, no need to worry about this on your end!

**Comment by keithpitt** [comment]
💃
