### ISSUE TITLE
Pipelines with a slash don't work

### ISSUE THREAD

**Issue by EvHaus** [chronotc/monorepo-diff-buildkite-plugin#27]
Looks like either this plugin (or maybe Buildkite's API) doesn't support triggering a pipeline that has a `/` in the name (ie. `foo/bar`). You get a 422 error:

```

2020-06-19 23:40:37 ERROR  Unrecoverable error, skipping retries
--
  | 2020-06-19 23:40:37 FATAL  Failed to upload and process pipeline: POST https://agent.buildkite.com/v3/jobs/44176033-bf4f-4ca9-8370-d90809786225/pipelines: 422 Pipeline "foo/bar" does not exist
  | 🚨 Error: The command exited with status 1
```

My pipeline is defined as:

```
steps:
  - label: 'Triggering pipelines'
    plugins:
      - chronotc/monorepo-diff#v1.1.1:
          watch:
            - path: 'packages/something'
              config:
                trigger: 'foo/bar'
```

Removing the slash from the name of the pipeline makes it work.

**Comment by chronotc** [comment]
The trigger step uses the pipeline slug.
Pipeline slugs will not have slashes in them.

If the pipeline was created with a slash,
ie. `foo/bar`
it should have a corresponding slug of `foo-bar`.
