### ISSUE TITLE
Update default diff checking logic?

### ISSUE THREAD

**Issue by evandam** [chronotc/monorepo-diff-buildkite-plugin#31]
I haven't been using this plugin too extensively, but I was curious if the `git diff` logic could have a slightly more sensible default.

In general, I think open PRs (or branches) should always diff against master (or default branch) since you might not trigger a required pipeline on every commit.

For example:
- You make a huge new feature
- The tests fail
- You edit `README.md` that doesn't trigger any pipelines
- You get a green build since no tests were run.

This seems like a pitfall a ton of users can fall into.

Something like this might be a good alternative?

```bash
if [ "$BUILDKITE_BRANCH" = "$BUILDKITE_PIPELINE_DEFAULT_BRANCH" ]; then
  git diff --name-only HEAD~1
else
  git diff --name-only "origin/$BUILDKITE_PIPELINE_DEFAULT_BRANCH"
fi
```

It's easy enough to drop a custom script in here, but food for thought!

**Comment by worxli** [comment]
We use exactly the same diff script as @evandam and I think it would be a good default.

**Comment by worxli** [comment]
What we also needed to add is `git fetch origin $BUILDKITE_PIPELINE_DEFAULT_BRANCH:$BUILDKITE_PIPELINE_DEFAULT_BRANCH`, just to be sure that e.g. master is up to date.

**Comment by adikari** [comment]
Sounds good. I am happy to merge it if you create a PR.

**Comment by adikari** [comment]
As we don't have much feed back from the users on their diff requirements. For now I suggest you put your diff script in a file then use that in the diff config of the pipeline definition.
