### ISSUE TITLE
Add an option to use a pre-downloaded binary vs downloading it every time

### ISSUE THREAD

**Issue by rajatvig** [chronotc/monorepo-diff-buildkite-plugin#68]
The plugin downloads the binary every time the build is run which takes time. Instead could there be an option to assume the binary is in `/usr/bin`?

**Comment by adikari** [comment]
@rajatvig the executable is 3 MB so the download should not add any significant time to your builds. At least that's the case for me but I am not sure about your scenario. It literally downloads the binary in 1 second. 

![image](https://user-images.githubusercontent.com/1757714/133631993-8d5eae95-3366-4ff5-a81f-4287e6e3e619.png)

**Comment by adikari** [comment]
I am also not sure how you are running your builds. Are you planning to download the binary manually at chuck it in a directory on your build machine? To me, this feels like optimization with not much to gain. Let me know if you think otherwise or details of your scenario.

**Comment by adikari** [comment]
It would be nice if you could also update the test to include the new property https://github.com/chronotc/monorepo-diff-buildkite-plugin/blob/master/tests/command.bats#L96

**Comment by rajatvig** [comment]
@adikari Thanks for looking at the issue. Will update the PR as commented soon.

There are two issues
1. We run too many builds a day and every build downloading the binary is wasteful considering the binary does not actually change.
2. Downloading binaries at build time is a security risk for us. We have disabled all plugins other than approved ones.

With regards to the question on packaging the binary, we are baking in a custom docker image and a compute image with the agent and this binary and running it as a container or VM varying on what the build needs to do.

Hope that explains the issue better
